if(EXISTS "C:/Users/brams/source/repos/FindWhat Project/src/utils/test/test_USystem-b12d07c_tests.cmake")
  include("C:/Users/brams/source/repos/FindWhat Project/src/utils/test/test_USystem-b12d07c_tests.cmake")
else()
  add_test(test_USystem_NOT_BUILT-b12d07c test_USystem_NOT_BUILT-b12d07c)
endif()
